### ISSUE TITLE
[info_terminal_gui] Doesn't start when started from a launch file

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#103]
Apparently `web.py` assumes that the `name` tag in the launch file represents the port. This is the error:

```
Init ROS node.
Web server starting..
Traceback (most recent call last):
  File "/localhome/strands/aaf_ws/src/aaf_deployment/info_terminal/info_terminal_gui/scripts/info_terminal.py", line 146, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 313, in run
    return wsgi.runwsgi(self.wsgifunc(*middleware))
  File "/usr/local/lib/python2.7/dist-packages/web/wsgi.py", line 54, in runwsgi
    return httpserver.runsimple(func, validip(listget(sys.argv, 1, '')))
  File "/usr/local/lib/python2.7/dist-packages/web/net.py", line 76, in validip
    port = int(port)
ValueError: invalid literal for int() with base 10: '=info_terminal_gui'
[info_terminal_gui-3] process has died [pid 25002, exit code 1, cmd /localhome/strands/aaf_ws/src/aaf_deployment/info_terminal/info_terminal_gui/scripts/info_terminal.py __name:=info_terminal_gui __log:=/localhome/strands/.ros/log/f56d9904-de49-11e4-8b9d-00032d225887/info_terminal_gui-3.log].
log file: /localhome/strands/.ros/log/f56d9904-de49-11e4-8b9d-00032d225887/info_terminal_gui-3*.log
```

This is the launch file statement that doesn't work:

```
<node pkg="info_terminal_gui" type="info_terminal.py" name="info_terminal_gui" output="screen"/>
```

**Comment by marc-hanheide** [comment]
Is fixed by #105
