### ISSUE TITLE
[file manager] upload problems

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#236]
hey @cdondrup @marc-hanheide @mzillich 

I cannot upload any picutres in the file manager.

what can be the problem?

I thought about the file size but I already uploaded one pic with a quite big size and there it went very well

**Comment by cdondrup** [comment]
This might have something to do with it:

```
192.168.200.69:65346 - - [18/May/2015 14:04:02] "HTTP/1.1 GET /get_media_thumb/5559c97b68124427c1a065c5" - 500 Internal Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "/opt/ros/indigo/lib/mongodb_media_server/server.py", line 243, in GET
    im.thumbnail(size, Image.ANTIALIAS)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1583, in thumbnail
    self.load()
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 218, in load
    raise IOError("image file is truncated (%d bytes not processed)" % len(b))
IOError: image file is truncated (33 bytes not processed)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "/opt/ros/indigo/lib/mongodb_media_server/server.py", line 243, in GET
    im.thumbnail(size, Image.ANTIALIAS)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1583, in thumbnail
    self.load()
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 218, in load
    raise IOError("image file is truncated (%d bytes not processed)" % len(b))
IOError: image file is truncated (11 bytes not processed)


Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "/opt/ros/indigo/lib/mongodb_media_server/server.py", line 243, in GET
    im.thumbnail(size, Image.ANTIALIAS)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1583, in thumbnail
    self.load()
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 218, in load
    raise IOError("image file is truncated (%d bytes not processed)" % len(b))
IOError: image file is truncated (19 bytes not processed)
```

Maybe @marc-hanheide or @cburbridge have an idea... Otherwise, can some one delete the picture from the data centre? @marc-hanheide ?

**Comment by denisehe** [comment]
@cdondrup @marc-hanheide 
good morning, upload works perfectly now :-) 

a question to you @cdondrup: are the pictures on the robot shown always in the same order or randomly?

**Comment by cdondrup** [comment]
In the same order.

**Comment by denisehe** [comment]
ok - would it be easy to switch to a random mode?

if not same order is okay. I just thought that it might enhances interest if another picture is visible in the beginning motivating persons to click further.

what do you think?

**Comment by cdondrup** [comment]
Really random wouldn't be a problem. Intelligent random (not showing images twice) might. That could be changed but since I am leaving for two weeks on Sunday, I don't have time to change things that are working, sorry. If someone else volunteers, it shouldn't be too hard.

**Comment by denisehe** [comment]
normal random would be fine! no further wishes ;-)

could you do that before you leave or do I have to ask somebody else to do it?

oh, cool where do you go?

**Comment by cdondrup** [comment]
I am going to Seattle and have a lot of other stuff to do before I leave. This would be very low on my priority list, sorry. I can try but I wouldn't count on it being done in time.

**Comment by denisehe** [comment]
@cdondrup ok no problem - so have a good flight and nice time overseas! I will ask mark - so no worries about it!

@marc-hanheide: hi, as discussed with christian - would it be possible for you to change the picture galaery to a simple random mode? I think it would be more engaging if the galeriy starts with different pictures thus inducing a kind of novelty effect for persons who already had a look at the robot

**Comment by marc-hanheide** [comment]
I can only confirm what @cdondrup said, nice to have, but low on my priority list, I'm afraid. It's marking crazyness these days and I cannot afford to further fall behind with that.

**Comment by marc-hanheide** [comment]
please open a new issue for this and assign me, then there's a chance I'll take care of it early next week.
