### ISSUE TITLE
Walking group failed to start

### ISSUE THREAD

**Issue by Jailander** [strands-project/aaf_deployment#386]
Today the walking group did not start the log is here 
[WG_fail.txt](https://github.com/strands-project/aaf_deployment/files/624728/WG_fail.txt)

error in short:

```bash
[ERROR] [WallTime: 1480599627.188612] bad callback: <bound method RecoveryFeedback.state_cb of <__main__.RecoveryFeedback object at 0x7fac4f75cc10>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/strands/aaf_ws/src/aaf_deployment/aaf_walking_group/scripts/walking_group_recovery_feedback.py", line 55, in state_cb
    if msg.status_list[-1].status == 1:
IndexError: list index out of range
```

**Comment by cdondrup** [comment]
https://github.com/strands-project/aaf_deployment/pull/384 fixed that. Please update.

But that means it never received a move_base goal... did you restart navigation directly before that?
