### ISSUE TITLE
The origin for the sensor at `XXX` is out of map bounds. So, the costmap cannot raytrace for it.

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#392]
can this have something to do with the costmaps for `human_aware`, @cdondrup?

e.g. http://answers.ros.org/question/9845/move_base-warning-sensor-out-of-bounds/

**Comment by marc-hanheide** [comment]
I also saw this right before:

```
Exception in your execute callback: 'NoneType' object has no attribute 'tell' Traceback (most recent call last): 
File "/opt/ros/indigo/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 291, in executeLoop self.execute_callback(goal) 
File "/home/strands/aaf_ws/src/strands_hri/strands_human_aware_navigation/scripts/human_aware_navigation.py", line 199, in goalCallback self.resetSpeed() 
File "/home/strands/aaf_ws/src/strands_hri/strands_human_aware_navigation/scripts/human_aware_navigation.py", line 122, in resetSpeed self.client.update_configuration(self.fast_param) 
File "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/client.py", line 219, in update_configuration msg = self._set_service(config).config 
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__ return self.call(*args, **kwds) 
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 512, in call transport.send_message(request, self.seq) 
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 634, in send_message serialize_message(self.write_buff, seq, msg) 
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/msg.py", line 139, in serialize_message start = b.tell() AttributeError: 'NoneType' object has no attribute 'tell'
```

**Comment by marc-hanheide** [comment]
I'm asking as it only seems to happen for `human_nav` edges, but I can't be sure.

**Comment by marc-hanheide** [comment]
A restart of navigation solved it, but I don't consider this a solution. Can we please investigate once everybody returned.

**Comment by marc-hanheide** [comment]
I had this one again... Here's the full log from tmux: https://gist.github.com/marc-hanheide/1eca01323b57352cbfae77efa0786b71

**Comment by cdondrup** [comment]
The current human-aware navigation does not change any costmap parameters but just the min and max speeds for translation and rotation. I don't think that should cause this error but am not sure. I still have no idea how to solve the issue with the dynamic reconfigure not working. I could just catch the `AttributeError` and retry as a first step.
